image: microsoft/dotnet:2.1-sdk-alpine

stages:
  - build
  - test
  - deploy


before_script:
  - "dotnet restore"

build ChickenAPI:
  stage: build
  tags:
    - docker
    - dotnet
  variables:
    build_path: "src/ChickenAPI"
  script:
    - "cd $build_path"
    - "dotnet build"
    
test ChickenAPI:
  stage: test
  tags:
    - docker
    - dotnet
  variables:
    build_path: "test/ChickenAPI.Test"
  script:
    - "cd $build_path"
    - "dotnet test"