image: microsoft/dotnet:2.1-sdk-alpine

stages:
  - build
  - test
  - deploy

tags:
  - docker
  - dotnet


before_script:
  - "dotnet restore"

build SDK.Core:
  stage: build
  variables:
    build_path: "src/ChickenAPI"
  script:
    - "cd $build_path"
    - "dotnet build"